//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentals
    {
        public int ID { get; set; }
        public int Customer { get; set; }
        public int Employee { get; set; }
        public int Copy { get; set; }
        public System.DateTime RentedAt { get; set; }
        public System.DateTime GivedBackAt { get; set; }
        public decimal PricePerDay { get; set; }
        public int MaxDays { get; set; }
        public decimal Total { get; set; }
    
        public virtual Copies Copies { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
